server:
  port: ${PORT:9007}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: postRoute
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**
        - id: tagRoute
          uri: lb://TAG-SERVICE
          predicates:
            - Path=/tags/**
        - id: voteRoute
          uri: lb://VOTE-SERVICE
          predicates:
            - Path=/votes/**

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
