server:
  port: ${PORT:9010}

spring:
  application:
    name: vote-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5435}/${POSTGRES_DB:vote-user}
    username: ${POSTGRES_USER:vote-user}
    password: ${POSTGRES_PASSWORD:123123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current-session-context-class: thread
        format-sql: true
        jdbc:
          lob:
            non-contextual-creation: true

kafka:
  brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
