global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "discovery-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["discovery-service:8761"]

  - job_name: "config-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["config-service:9006"]

  - job_name: "gateway-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway-service:9007"]

  - job_name: "post-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["post-service:9008"]

  - job_name: "tag-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["tag-service:9009"]

  - job_name: "vote-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["vote-service:9010"]
